version: '3.8'
services:
  backend:
    build: ./backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    environment:
      - TELEGRAM_BOT_TOKEN
    depends_on:
      - backend
